#\u8BBE\u7F6E\u7AEF\u53E3\u53F7
server:
  port: 8081
#\u8BBE\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u6CD5
mybatis:
  type-aliases-package: mapper.tangkc.mybatis.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#\u6DFB\u52A0mybatis-config.xml\u8DEF\u5F84\u548Cmapper.xml\u8DEF\u5F84
